version: '3.9'

services:
 db:
   image: postgres:latest
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
   ports:
     - "5433:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - ./intifadahactivity/.env

 intifadah-web:
   build: .
   container_name: intifadah-docker
   ports:
     - "8001:8000"
   depends_on:
     - db
   environment:
     DJANGO_SECRET_KEY: ${SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${LOG_LEVEL}
     DATABASE_ENGINE: ${DB_ENGINE}
     DATABASE_NAME: ${DB_NAME}
     DATABASE_USERNAME: ${DB_USER}

     DATABASE_PASSWORD: ${DB_PASSWORD}
     DATABASE_HOST: ${DB_HOST}
     DB_PORT: ${DB_PORT}
   env_file:
     - ./intifadahactivity/.env
volumes:
   postgres_data:
