version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:5432 --
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:9000 intifadahactivity.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: intifadah-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: v1d14ry4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

volumes:
  static_volume:
  media_volume:
  postgres_data:
  static:

networks:
  app-network:
