# Generated by Django 5.2 on 2025-05-14 03:43

import django.db.models.deletion
import managementactivity.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Activity Types',
                'db_table': 'activity_types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MasterIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('MonthlyIncome', models.IntegerField()),
                ('PositionIncome', models.IntegerField()),
                ('HistoryIncome', models.IntegerField()),
                ('VariableIncome', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Master Incomes',
                'db_table': 'master_incomes',
                'ordering': ('MonthlyIncome',),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ('phone',),
            },
        ),
        migrations.CreateModel(
            name='ActivityApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('UserId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ActivityTypeId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='managementactivity.activitytype')),
            ],
            options={
                'verbose_name_plural': 'Activity Approvals',
                'db_table': 'activity_approvals',
            },
        ),
        migrations.CreateModel(
            name='ManagerialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ActivityDetail', models.TextField()),
                ('ActivityResult', models.TextField(null=True)),
                ('ActivityScore', models.IntegerField(null=True)),
                ('ActivityImage', models.ImageField(blank=True, default='blank.png', upload_to='uploads/')),
                ('RejectedReason', models.TextField(null=True)),
                ('ActivityDateTime', models.IntegerField()),
                ('ActivityStatus', models.IntegerField(choices=managementactivity.utils.ActivityStatus.choices, default=managementactivity.utils.ActivityStatus['WAITING_APPROVAL'])),
                ('ApprovedAt', models.IntegerField(null=True)),
                ('ApprovedById', models.IntegerField(null=True)),
                ('ActivityType', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='managementactivity.activitytype')),
                ('ManagerialUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Managerial Activities',
                'db_table': 'managerial_activities',
                'permissions': [('update_activity_status', 'Dapat merubah status aktivitas')],
            },
        ),
    ]
