# Generated by Django 5.2 on 2025-05-06 04:38

import django.db.models.deletion
import managementactivity.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Activity Types',
                'db_table': 'activity_types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MasterIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('MonthlyIncome', models.IntegerField()),
                ('PositionIncome', models.IntegerField()),
                ('HistoryIncome', models.IntegerField()),
                ('VariableIncome', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Master Incomes',
                'db_table': 'master_incomes',
                'ordering': ('MonthlyIncome',),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ('phone',),
            },
        ),
        migrations.CreateModel(
            name='ManagerialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ActivityDetail', models.TextField()),
                ('ActivityDateTime', models.DateTimeField()),
                ('ActivityResult', models.TextField()),
                ('ActivityScore', models.IntegerField()),
                ('ActivityImage', models.TextField()),
                ('RejectedReason', models.TextField()),
                ('ActivityStatus', models.IntegerField(choices=managementactivity.utils.ActivityStatus.choices, default=managementactivity.utils.ActivityStatus['WAITING_APPROVAL'])),
                ('ApprovedAt', models.DateTimeField()),
                ('ApprovedById', models.IntegerField()),
                ('ActivityTypeId', models.ManyToManyField(to='managementactivity.activitytype')),
                ('ManagerialUserId', models.ManyToManyField(to='managementactivity.users')),
            ],
            options={
                'verbose_name_plural': 'Managerial Activities',
                'db_table': 'managerial_activities',
                'ordering': ('ActivityDateTime',),
            },
        ),
        migrations.CreateModel(
            name='ActivityApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ActivityTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementactivity.activitytype')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementactivity.users')),
            ],
            options={
                'verbose_name_plural': 'Activity Approvals',
                'db_table': 'activity_approvals',
                'ordering': ('ActivityTypeId',),
            },
        ),
    ]
