# Generated by Django 5.2 on 2025-05-07 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityapproval',
            options={'verbose_name_plural': 'Activity Approvals'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.RemoveField(
            model_name='activityapproval',
            name='ActivityTypeId',
        ),
        migrations.RemoveField(
            model_name='activityapproval',
            name='UserId',
        ),
        migrations.AlterField(
            model_name='managerialactivity',
            name='ManagerialUserId',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='activityapproval',
            name='ActivityTypeId',
            field=models.ManyToManyField(to='managementactivity.activitytype'),
        ),
        migrations.AddField(
            model_name='activityapproval',
            name='UserId',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
