# Generated by Django 5.2 on 2025-05-07 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0002_alter_activityapproval_options_remove_users_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityapproval',
            name='ActivityTypeId',
        ),
        migrations.RemoveField(
            model_name='activityapproval',
            name='UserId',
        ),
        migrations.AddField(
            model_name='activityapproval',
            name='ActivityTypeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='managementactivity.activitytype'),
        ),
        migrations.AddField(
            model_name='activityapproval',
            name='UserId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
