# Generated by Django 5.2 on 2025-05-07 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0004_remove_managerialactivity_activitytypeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerialactivity',
            old_name='ManagerialUserId',
            new_name='UserId',
        ),
    ]
