# Generated by Django 5.2 on 2025-05-07 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0005_rename_managerialuserid_managerialactivity_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerialactivity',
            old_name='UserId',
            new_name='ManagerialUser',
        ),
    ]
