# Generated by Django 5.2 on 2025-05-07 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0006_rename_userid_managerialactivity_managerialuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerialactivity',
            old_name='ActivityTypeId',
            new_name='ActivityType',
        ),
    ]
