# Generated by Django 5.2 on 2025-05-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0007_rename_activitytypeid_managerialactivity_activitytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerialactivity',
            options={'verbose_name_plural': 'Managerial Activities'},
        ),
        migrations.RemoveField(
            model_name='managerialactivity',
            name='ActivityDateTime',
        ),
    ]
