# Generated by Django 5.2 on 2025-05-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0008_alter_managerialactivity_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerialactivity',
            old_name='ApprovedById',
            new_name='ActivityDateTime',
        ),
        migrations.RemoveField(
            model_name='managerialactivity',
            name='ApprovedAt',
        ),
    ]
