# Generated by Django 5.2 on 2025-05-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0009_rename_approvedbyid_managerialactivity_activitydatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerialactivity',
            name='ApprovedAt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='managerialactivity',
            name='ApprovedById',
            field=models.IntegerField(default=0),
        ),
    ]
