# Generated by Django 5.2 on 2025-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0010_managerialactivity_approvedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerialactivity',
            name='ActivityImage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='managerialactivity',
            name='ActivityResult',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='managerialactivity',
            name='ActivityScore',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='managerialactivity',
            name='ApprovedAt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='managerialactivity',
            name='ApprovedById',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='managerialactivity',
            name='RejectedReason',
            field=models.TextField(null=True),
        ),
    ]
