# Generated by Django 5.2 on 2025-05-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0011_alter_managerialactivity_activityimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerialactivity',
            name='ActivityImage',
        ),
    ]
