# Generated by Django 5.2 on 2025-05-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0012_remove_managerialactivity_activityimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerialactivity',
            name='ActivityImage',
            field=models.ImageField(blank=True, default='blank.png', upload_to='uploads/'),
        ),
    ]
