# Generated by Django 5.2 on 2025-05-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0013_managerialactivity_activityimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerialactivity',
            options={'permissions': [('can_update_activity_status', 'Dapat merubah status aktivitas')], 'verbose_name_plural': 'Managerial Activities'},
        ),
    ]
