# Generated by Django 5.2 on 2025-05-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementactivity', '0014_alter_managerialactivity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerialactivity',
            options={'permissions': [('update_ActivityStatus', 'Dapat merubah status aktivitas')], 'verbose_name_plural': 'Managerial Activities'},
        ),
    ]
