# Generated by Django 5.2 on 2025-06-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'general settings',
                'db_table': 'general_settings',
                'ordering': ('name',),
            },
        ),
    ]
