# Generated by Django 5.2 on 2025-05-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Income Settings',
                'db_table': 'income_settings',
                'ordering': ('key',),
            },
        ),
    ]
