# Generated by Django 5.2 on 2025-06-04 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomecalculation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerialIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_score', models.DecimalField(decimal_places=0, max_digits=20)),
                ('history_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('position_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fix_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('variable_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Managerial Incomes',
                'db_table': 'managerial_incomes',
                'ordering': ('index',),
            },
        ),
    ]
