# Generated by Django 5.2 on 2025-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomecalculation', '0002_managerialincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerialincome',
            name='month',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
