# Generated by Django 5.2 on 2025-06-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomecalculation', '0004_managerialfixincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerialfixincome',
            name='history_income_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='managerialfixincome',
            name='position_income_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='managerialincome',
            name='index',
            field=models.FloatField(),
        ),
    ]
