# Generated by Django 5.2 on 2025-06-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomecalculation', '0005_alter_managerialfixincome_history_income_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerialfixincome',
            name='history_income_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='managerialfixincome',
            name='position_income_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
