# Generated by Django 5.2 on 2025-06-03 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posmaster', '0002_generalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitGeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=255)),
                ('general_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posmaster.generalsettings')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posmaster.unitmaster')),
            ],
            options={
                'verbose_name_plural': 'unit general settings',
                'db_table': 'unit_general_settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=255)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posmaster.paymentmethod')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posmaster.unitmaster')),
            ],
            options={
                'verbose_name_plural': 'unit payment methods',
                'db_table': 'unit_payment_methods',
                'ordering': ['-created_at'],
            },
        ),
    ]
